spring.datasource.url=jdbc:mariadb://localhost:3306/minecraftWeb
spring.datasource.username=root
spring.datasource.password=bsdb
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.profiles.active=local